# Generated by Django 5.2.5 on 2025-08-30 10:53

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='product_images/'),
        ),
    ]
